sudo: required

language: node_js
node_js:
  - 9

services:
  - docker

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js

after_deploy:
  - echo "Done deploying!"