sudo: required

language: node_js
node_js:
  - 9

services:
  - docker

script:
  - npm test

after_success:
  - cat ./coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
  - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js